"""
app/agents/executor.py
───────────────────────
The Executor Agent — Task dispatcher.

WHAT THIS FILE DOES
────────────────────
- Take the approved JSON SOP plan (generated by Planner, approved by HITL)
- Loop through the prioritized tasks
- Find the nearest available L2/L3 TrustedNode to assign each task
- Create a `TaskAssignment` record in PostgreSQL
- Call the Twilio service to dispatch the SMS
"""
import logging
import uuid
from typing import Any

from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession
from fastapi import HTTPException

from app.models import ActiveCrisis, TrustedNode, TaskAssignment
from app.services import twilio_client

logger = logging.getLogger(__name__)


async def dispatch_tasks(db: AsyncSession, crisis: ActiveCrisis, plan: dict[str, Any]):
    """
    Take the approved plan and assign tasks to nearest available nodes.
    """
    tasks = plan.get("tasks", [])
    if not tasks:
        logger.warning(f"Executor: No tasks found in plan for crisis {crisis.id}")
        return

    logger.info(f"🚀 Executor: Dispatching {len(tasks)} tasks for crisis {crisis.id}")

    # 1. Find all available L2/L3 nodes within 10km of the crisis
    # (fallback to 50km if none found, but keep it simple for hackathon)
    # We will just fetch all active L2/L3 nodes for now and sort by distance in code, 
    # or rely on PostGIS order
    
    # Check if crisis has location
    if not crisis.location:
        logger.warning(f"Executor: Crisis {crisis.id} has no location. Cannot purely route geographically. Will attempt to fetch any active L2/L3.")
        nodes_query = select(TrustedNode).where(
            TrustedNode.is_active == True,
            TrustedNode.tier >= 2
        )
    else:
        # Distance calculation in PostGIS
        nodes_query = select(
            TrustedNode
        ).where(
            TrustedNode.is_active == True,
            TrustedNode.tier >= 2,
            TrustedNode.location.is_not(None)
        ).order_by(
            func.ST_Distance(TrustedNode.location, crisis.location)
        ).limit(10)  # Get top 10 nearest L2/L3 nodes

    result = await db.execute(nodes_query)
    available_nodes = result.scalars().all()

    if not available_nodes:
        logger.error(f"Executor: DEADLOCK. No active L2/L3 nodes found to assign {len(tasks)} tasks.")
        return

    # Super naive round-robin assignment for demonstration purposes
    # In reality, you'd match task.resource_needed to node.capabilities
    node_count = len(available_nodes)
    
    for i, task in enumerate(tasks):
        assigned_node = available_nodes[i % node_count]
        
        # Create TaskAssignment record
        assignment = TaskAssignment(
            id=uuid.uuid4(),
            crisis_id=crisis.id,
            node_id=assigned_node.id,
            task_description=f"[{task.get('priority', 'MEDIUM')}] {task.get('action', 'Unknown Task')}",
            status="PENDING"
        )
        db.add(assignment)
        await db.flush()

        logger.info(f"   ↳ Task {assignment.id} assigned to {assigned_node.name} (Tier {assigned_node.tier})")
        
        # Call Twilio to dispatch the actual SMS
        await twilio_client.dispatch_task_sms(
            db=db,
            node=assigned_node,
            task=task,
            crisis=crisis,
            assignment_id=assignment.id
        )

    # Note: We do a final commit at the end of the API request
    logger.info("✅ Executor: All tasks dispatched successfully.")
